-- MySQL Script generated by MySQL Workbench
-- 02/11/15 15:19:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `country_id` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country10`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disponibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disponibility` (
  `disponibility_id` INT NOT NULL,
  `morning` INT NULL,
  `afternoon` INT NULL,
  `night` INT NULL,
  `allday` INT NULL,
  PRIMARY KEY (`disponibility_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`day` (
  `day_id` INT NOT NULL,
  `day` VARCHAR(45) NULL,
  PRIMARY KEY (`day_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sport` (
  `sport_id` INT NOT NULL,
  `name_sport` VARCHAR(45) NULL,
  PRIMARY KEY (`sport_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team` (
  `team_id` INT NOT NULL,
  `team_name` VARCHAR(45) NULL,
  `nb_player` INT NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `city_id` INT NOT NULL,
  `day_id` INT NOT NULL,
  `sport_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  `days` VARCHAR(45) NULL,
  `path_photo` VARCHAR(45) NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time`  NULL,
  INDEX `fk_users_city_idx` (`city_id` ASC),
  INDEX `fk_users_day1_idx` (`day_id` ASC),
  INDEX `fk_users_sport1_idx` (`sport_id` ASC),
  INDEX `fk_users_team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_users_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_day1`
    FOREIGN KEY (`day_id`)
    REFERENCES `mydb`.`day` (`day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_sport1`
    FOREIGN KEY (`sport_id`)
    REFERENCES `mydb`.`sport` (`sport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`day` (
  `day_id` INT NOT NULL,
  `day` VARCHAR(45) NULL,
  PRIMARY KEY (`day_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`month` (
  `month_id` INT NOT NULL,
  `month` VARCHAR(45) NULL,
  `day_id` INT NOT NULL,
  PRIMARY KEY (`month_id`, `day_id`),
  INDEX `fk_month_day1_idx` (`day_id` ASC),
  CONSTRAINT `fk_month_day1`
    FOREIGN KEY (`day_id`)
    REFERENCES `mydb`.`day` (`day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`year` (
  `year_id` INT NOT NULL,
  `year` INT NULL,
  `month_id` INT NOT NULL,
  PRIMARY KEY (`year_id`, `month_id`),
  INDEX `fk_year_month1_idx` (`month_id` ASC),
  CONSTRAINT `fk_year_month1`
    FOREIGN KEY (`month_id`)
    REFERENCES `mydb`.`month` (`month_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calendar` (
  `year_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`year_id`),
  INDEX `fk_calendar_year1_idx` (`year_id` ASC),
  CONSTRAINT `fk_calendar_year1`
    FOREIGN KEY (`year_id`)
    REFERENCES `mydb`.`year` (`year_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `country_id` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country10`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`map` (
  `city_id` INT NOT NULL,
  `name_stadium` VARCHAR(45) NULL,
  INDEX `fk_map_city_copy11_idx` (`city_id` ASC),
  CONSTRAINT `fk_map_city_copy11`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`monday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monday` (
  `monday_id` INT NOT NULL,
  `moment_id` INT NULL,
  `monday` INT NULL,
  `moment_moment_id` INT NOT NULL,
  PRIMARY KEY (`monday_id`),
  INDEX `fk_monday_moment1_idx` (`moment_moment_id` ASC),
  CONSTRAINT `fk_monday_moment1`
    FOREIGN KEY (`moment_moment_id`)
    REFERENCES `mydb`.`day` (`day_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
